# Site settings
title: Presteigne Chess Club
email: kevin@saull.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "http://presteignechess.club" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, bower_components, bower.json, gulpfile.js, Gemfile, Gemfile.lock]
gems:
  - jekyll-sitemap